export const IDLE_TITLES: string[] = [
  '$ idle...',
  '$ tail -f activity.log',
  '[ AFK ] zZz',
  '$ make coffee',
  '$ vim ~/life.md',
  '$ git stash --include-untracked',
  '$ ssh user@you ...',
  '$ npm run procrastinate',
  '$ rm -rf bugs/',
  '[ OK ] focus.mode: lost',
  '$ ping localhost ...',
  '$ cat /dev/random',
  '$ sudo apt install motivation',
  'compiling thoughts...',
  'you closed the tab? :(',
  '$ uptime · 99 days',
  '$ history | grep "this idea"',
  '42 unread notifications',
];
